from flask import Flask, request, jsonify
from retrieval import LegalRetriever
from openai import OpenAI
from config import Config

# Initialize the Flask app and configurations
app = Flask(__name__)
app.config.from_object(Config)

# Initialize OpenAI client and LegalRetriever
client = OpenAI(api_key=app.config["OPENAI_API_KEY"])
retriever = LegalRetriever()


def summarize_text(text):
    # Summarize the text to reduce length
    response = client.completions.create(
        model="gpt-3.5-turbo-instruct",
        prompt=f"Summarize this document:\n\n{text}",
        max_tokens=200,  # Adjust based on summarization needs
        temperature=0.5,
    )
    return response.choices[0].text.strip()


def generate_answer(query):
    # Step 1: Retrieve fewer documents (e.g., top 3) to reduce the overall prompt length
    relevant_docs = retriever.retrieve_documents(query, k=3)

    # Step 2: Summarize or truncate each document to keep the prompt within token limits
    summarized_docs = [
        summarize_text(doc[:500]) for doc in relevant_docs
    ]  # Summarize and truncate
    context_text = "\n\n".join(
        [f"Document {i+1}: {summary}" for i, summary in enumerate(summarized_docs)]
    )

    # Step 3: Create the prompt with the summarized/truncated documents and user question
    prompt = f"{context_text}\n\nUser question: {query}\nAnswer:"

    # Step 4: Generate a shorter answer by limiting max_tokens for the completion
    response = client.completions.create(
        model="gpt-3.5-turbo-instruct",
        prompt=prompt,
        max_tokens=100,  # Adjust to control answer length
        temperature=0.7,
    )
    answer = response.choices[0].text.strip()

    return {
        "rag_context": context_text,  # Context generated from RAG
        "openai_answer": answer,  # Answer generated by OpenAI
    }


@app.route("/api/query", methods=["POST"])
def answer_query():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Invalid or missing JSON data"}), 400

    query = data.get("query", "")
    if not query:
        return jsonify({"error": "Query not provided"}), 400

    # Generate the answer and context information
    result = generate_answer(query)

    return jsonify(
        {
            "query": query,
            "rag_context": result["rag_context"],
            "openai_answer": result["openai_answer"],
        }
    )


if __name__ == "__main__":
    app.run(debug=True)
